import Head from 'next/head'
import Link from 'next/link'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Devter 🐦</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>
          <a href="https://nextjs.org">devter</a>
        </h1>
        <nav>
          <Link href="/timeline">
            <a>Timeline</a>
          </Link>
        </nav>
      </main>
      <style jsx>{`
        h1 {
          text-align: center;
          font-size: 48px;
        }
        nav {
          font-size: 24px;
          text-align: center;
        }
        a {
          color: tomato;
          text-decoration: none;
        }
      `}</style>
    </div>
  )
}
